apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: greentube
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: greentube
  targetCPUUtilizationPercentage: 50
